SampleExample/my_app/catalog/models.py
from my_app import db

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    price = db.Column(db.Float)

    def __init__(self, name, price):
        self.name = name
        self.price = price

    def __repr__(self):
        return 'Product %d' % self.id

SampleExample/my_app/hello/models.py
MESSAGES = { 'default': 'Hello to the World of Flask!', }

SampleExample/my_app/product/models.py
PRODUCTS = { 
    'iphone': { 
        'name': 'iPhone 5S', 
        'category': 'Phones', 
        'price': 699, 
    },  
    'galaxy': { 
        'name': 'Samsung Galaxy 5', 
        'category': 'Phones', 
        'price': 649, 
    }, 
    'ipad-air': { 
        'name': 'iPad Air', 
        'category': 'Tablets', 
        'price': 649, 
    }, 
    'ipad-mini': { 
        'name': 'iPad Mini', 
        'category': 'Tablets', 
        'price': 549 
    } 
} 

SampleExample/my_app/__init__.py
# https://learning-oreilly-com.ezproxy.torontopubliclibrary.ca/library/view/flask-framework-cookbook/9781789951295/72adba2d-b200-46cf-9a6a-ba744eb71fff.xhtml
from flask import Flask
from flask_login import LoginManager ##Flask based Authentication
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///test.db'
app.config['SECRET_KEY'] = 'c1ecc4ba444d91d97d0da200bdde1da7' 
db = SQLAlchemy(app)

##Flask based Authentication # https://learning-oreilly-com.ezproxy.torontopubliclibrary.ca/library/view/flask-framework-cookbook/9781789951295/1d540388-bc11-41fd-a236-2b911a2fd1d0.xhtml
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'auth.auth_login'
##


from my_app.catalog.views import catalog_blueprint  #Blueprint
from my_app.hello.views import hello #  Blueprint
from my_app.product.views import product_blueprint #Blueprint
from my_app.auth.views import auth_blueprint #Blueprint

# import my_app.hello.views
# app.register_blueprint(hello)  #  Blueprint for 1st class
# app.register_blueprint(product_blueprint)  # BluePrint for 2nd class
app.register_blueprint(auth_blueprint)

db.create_all()

# Test URLs
# http://127.0.0.1:5000/
# http://127.0.0.1:5000/add/test1/GoodOneTest23
# http://127.0.0.1:5000/show/test1

SampleExample/my_app/catalog/views.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from my_app import db
from my_app.catalog.models import Product

catalog_blueprint = Blueprint('catalog', __name__)

@catalog_blueprint.route('/')
@catalog_blueprint.route('/home')
def catalog_home():
    return 'Welcome to Catalog home'


@catalog_blueprint.route('/product/<integer: id>')
def catalog_product(id):
    product = Product.query.get_or_404(id)
    return 'Product  - %s, $ %s' % (product.name, product.price)

@catalog_blueprint.route('/products')
def catalog_products():
    products = Product.query.all()
    res = {}
    for product in products:
        res[product:id] = { 'name': product.name, 'price': product.price }
    
    return jsonify(res)

@catalog_blueprint.route('/product-create', methods=['POST',])
def catalog_create_product():
    name = request.form.get('name')
    price = request.form.get('price')
    product = Product(name, price)
    db.session.add(product)
    db.session.commit()
    return '%s product is created ' % (product.name)

SampleExample/my_app/hello/views.py
# from my_app import app
from flask import Blueprint  #BluePrint
from flask import render_template, request, redirect, url_for

from my_app.hello.models import MESSAGES

hello = Blueprint('hello', __name__) #BluePrint

# @app.route('/')
# @app.route('/hello')
@hello.route('/hello')
def hello_world():
    return MESSAGES['default']

# @app.route('/show/<key>')
@hello.route('/show/<key>')
def get_message(key):
    return MESSAGES.get(key) or "%s not found!" % key

@hello.route('/add/<key>/<message>')
# @app.route('/add/<key>/<message>')
def add_or_update_message(key, message):
    MESSAGES[key] = message
    return "%s Added/Updated" % key

@hello.route('/insideview/<user>')
def hello_world1(user=None):
    user = user or 'Chander'
    return '''<html> 
    <head> 
      <title>Flask Framework Cookbook</title> 
 
    </head> 
      <body> 
        <h1>Hello %s!</h1> 
        <p>Welcome to the world of Flask!</p> 
      </body> 
</html     ''' % user

@hello.route('/hello3')
def hello3():
    user = request.args.get('user', 'Chander')
    return render_template('hello_index.html', user=user)

SampleExample/my_app/product/views.py
#from werkzeug.exceptions import abort
from flask import render_template, redirect, url_for
from flask import Blueprint
from my_app.product.models import PRODUCTS

product_blueprint=Blueprint('product', __name__)

@product_blueprint.route('/')
@product_blueprint.route('/home')
def product_home():
    return render_template('home_product.html', products=PRODUCTS)


@product_blueprint.route('/product/<key>')
def product(key):
    product = PRODUCTS.get(key)
    if not product:
        # abort(404)
        return "Error"
    return render_template('product.html', product=product)

SampleExample/my_app/templates/auth_home.html
{% extends 'base.html' %} 
{% block title %} {{ title }} {% endblock %}       
{% block container %} 
  <h1>Welcome to the Authentication Demo</h1> 
  {% if session.username %} 
    <h3>Hey {{ session.username }}!!</h3> 
    <a href="{{ url_for('auth.auth_logout') }}">Click here to 
       logout</a> 
  {% else %} 
  Click here to <a href="{{ url_for('auth.auth_login') }}">login</a> or 
      <a href="{{ url_for('auth.auth_register') }}">register</a> 
  {% endif %} 
{% endblock %} 

SampleExample/my_app/templates/auth_login.html
{% extends 'base.html' %} 
{% block title %} {{ title }} {% endblock %}       

 
{% block container %} 
  <div class="top-pad"> 
    <form 
        method="POST" 
        action="{{ url_for('auth.auth_login') }}" 
        role="form"> 
      {{ form.csrf_token }} 
      <div class="form-group">{{ form.username.label }}: {{ 
         form.username() }}</div> 
      <div class="form-group">{{ form.password.label }}: {{ 
         form.password() }}</div> 
      <button type="submit" class="btn btn-default">
         Submit</button> 
    </form> 
  </div> 
{% endblock %} 

SampleExample/my_app/templates/auth_registration.html
{% extends 'base.html' %} 
{% block title %} {{ title }} {% endblock %}       
{% block container %} 
  <div class="top-pad"> 
    <form 
        method="POST" 
        action="{{ url_for('auth.auth_register') }}" 
        role="form"> 
      {{ form.csrf_token }} 
      <div class="form-group">{{ form.username.label }}: {{ 
         form.username() }}</div> 
      <div class="form-group">{{ form.password.label }}: {{ 
         form.password() }}</div> 
      <div class="form-group">{{ form.confirm.label }}: {{ 
         form.confirm() }}</div> 
      <button type="submit" class="btn btn-default">
         Submit</button> 
    </form> 
  </div> 
{% endblock %} 

SampleExample/my_app/templates/base.html
<!DOCTYPE html> 
<html lang="en"> 
  <head> 
    <meta charset="utf-8"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <meta name="viewport" content="width=device-width, initial-
       scale=1"> 
    <title>
      {% block title %} {% endblock %}       
    </title> 
    <link href="{{ url_for('static', 
       filename='css/bootstrap.min.css') }}" rel="stylesheet"> 
    <link href="{{ url_for('static', filename='css/main.css') }}" 
       rel="stylesheet"> 
  </head> 
  <body> 
    {% if current_user.is_authenticated %}
    "You are authenticated " {{ current_user.username}}
    {% endif %}
    <div class="navbar navbar-inverse navbar-fixed-top" 
       role="navigation"> 
      <div class="container"> 
        <div class="navbar-header"> 
          <a class="navbar-brand" href="{{ url_for('auth.auth_home') 
             }}">Flask Cookbook</a> 
        </div> 
      </div> 
    </div> 
    <div class="container"> 
      {% block container %}{% endblock %} 
    </div> 
 
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> 
    <script src="https://ajax-googleapis-com.ezproxy.torontopubliclibrary.ca/ajax/libs/jquery/
       2.0.0/jquery.min.js"></script> 
           <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script> 
  </body> 
</html> 

SampleExample/my_app/templates/hello_index.html
<html> 
  <head> 
    <title>Flask Framework Cookbook</title> 
  </head> 
  <body> 
    <h1>Hello {{ user }}!</h1> 
    <p>Welcome to the world of Flask!</p> 
  </body> 
</html> 

SampleExample/my_app/templates/home_product.html
{% extends 'base.html' %} 
 
{% block container %} 
  <div class="top-pad"> 
    {% for id, product in products.items() %} 
      <div class="well"> 
        <h2> 
          <a href="{{ url_for('product.product', key=id) }}">{{ 
             product['name'] }}</a> 
          <small>$ {{ product['price'] }}</small> 
        </h2> 
      </div> 
    {% endfor %} 
  </div> 
{% endblock %}

SampleExample/my_app/templates/product.html
{% extends 'home_product.html' %} 
 
{% block container %} 
  <div class="top-pad"> 
    <h1>{{ product['name'] }} 
      <small>{{ product['category'] }}</small> 
    </h1> 
    <h3>$ {{ product['price'] }}</h3> 
  </div> 
{% endblock %} 